# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 13:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Edit',
            new_name='Post',
        ),
    ]
